### ISSUE TITLE
Error on opening browser in Anki 2.1.42

### ISSUE THREAD

**Issue by Regular-Opinion** [Liresol/anki-custom-shortcuts#108]
Debug info:
Anki 2.1.42 (8eebfe18) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-03-21 11:53:37

Caught exception:
Traceback (most recent call last):
  File "aqt\main.py", line 1067, in onBrowse
  File "aqt\__init__.py", line 101, in open
  File "aqt\browser.py", line 469, in __init__
  File "aqt\browser.py", line 531, in setupMenus
  File "aqt\hooks_gen.py", line 526, in __call__
  File "anki\hooks.py", line 34, in runHook
  File "C:\Users\HUZAIFA\AppData\Roaming\Anki2\addons21\24411424\custom_shortcuts.py", line 233, in cs_browser_setupShortcuts
    f.previewButton.setShortcut(config_scuts["window_browser preview"])
AttributeError: 'Ui_Dialog' object has no attribute 'previewButton'

**Comment by Liresol** [comment]
Hello,
It's probable that you're currently using an old version of the addon (possibly 7880764d4c) which isn't compatible with the current version of Anki. 
If you update the addon, the problem might go away.
If the issue remains even after you check for addon updates, then I will keep looking to see what the causes might be.

**Comment by Regular-Opinion** [comment]
Oh yes you are right. Thank you so much. This can be closed now.
