### ISSUE TITLE
Can't add a card to my deck

### ISSUE THREAD

**Issue by theprunner** [Liresol/anki-custom-shortcuts#112]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.44 (b2b3275f) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-05-28 14:12:14

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 36, in cmd
  File "aqt\webview.py", line 135, in _onCmd
  File "aqt\webview.py", line 580, in _onBridgeCmd
  File "aqt\toolbar.py", line 169, in _linkHandler
  File "aqt\toolbar.py", line 184, in _addLinkHandler
  File "aqt\main.py", line 1064, in onAddCard
  File "aqt\__init__.py", line 101, in open
  File "aqt\addcards.py", line 45, in __init__
  File "aqt\addcards.py", line 62, in setupChoosers
  File "aqt\modelchooser.py", line 32, in __init__
  File "<decorator-gen-20>", line 2, in setupModels
  File "anki\hooks.py", line 89, in decorator_wrapper
  File "anki\hooks.py", line 81, in repl
  File "C:\Users\s\AppData\Roaming\Anki2\addons21\24411424\custom_shortcuts.py", line 243, in cs_editorChangeNoteType
    QShortcut(QKeySequence(scut), self.widget, activated=self.on_activated)
TypeError: arguments did not match any overloaded call:
  QShortcut(QWidget): argument 1 has unexpected type 'QKeySequence'
  QShortcut(Union[QKeySequence, QKeySequence.StandardKey, str, int], QWidget, member: PYQT_SLOT = 0, ambiguousMember: PYQT_SLOT = 0, context: Qt.ShortcutContext = Qt.WindowShortcut): argument 2 has unexpected type 'builtin_function_or_method'

**Comment by Liresol** [comment]
Hello,

There's a chance that you're using an old version of the shortcut, since the code in the error points to what looks like old code (my guess it that it's [here](https://github.com/Liresol/anki-custom-shortcuts/commit/551efb746ebe9d7d2c9d1e4d2a8c30001189e74c#diff-c6fe461887610a94d0d199ae09113fe02964a1e58c7ded3fcbc97929864414a6) if you're curious).
If you update the addon, the error might go away.

If the error persists even after you update, then just let me know and I will look into it further.

**Comment by theprunner** [comment]
> Hello,
> 
> There's a chance that you're using an old version of the shortcut, since the code in the error points to what looks like old code (my guess it that it's [here](https://github.com/Liresol/anki-custom-shortcuts/commit/551efb746ebe9d7d2c9d1e4d2a8c30001189e74c#diff-c6fe461887610a94d0d199ae09113fe02964a1e58c7ded3fcbc97929864414a6) if you're curious).
> If you update the addon, the error might go away.
> 
> If the error persists even after you update, then just let me know and I will look into it further.

- I was running into a few other issues (like the known copy and paste issue) with the newest version, so i ended up downgrading to 2.1.40.

- I believe i did update to the new add-on version before downgrading, but i don't think that fixed the issue. I wish I have saved the error it said after updating the add-on so i could know if it was the same error.

- Thanks for looking at this and responding so quickly! I'm going to stick with the old version for now, but when I do upgrade again and there's an error I'll be sure to let you know and try and give more information next time.

**Comment by Liresol** [comment]
Oof, ok.
I'm going to leave this issue open for now, since there's likely an underlying issue in the current version.
If/when you encounter the issue in the newer versions, just paste any extra info you find and I'll look into it further.
