### ISSUE TITLE
New update issue

### ISSUE THREAD

**Issue by denisroutkevitch** [Liresol/anki-custom-shortcuts#114]
After updating addon (still using anki 2.1.40), got this issue. I was able to revert to previous version but just thought you should know.

```
Debug info:
Anki 2.1.40 (cf446733) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-06-03 08:25:12

Caught exception:
Traceback (most recent call last):
  File "aqt\main.py", line 1056, in onBrowse
  File "aqt\__init__.py", line 100, in open
  File "aqt\browser.py", line 611, in __init__
  File "C:\Users\Denis\AppData\Roaming\Anki2\addons21\24411424\custom_shortcuts.py", line 549, in cs_browser_setupEditor
    self.editor = Editor(self.mw, self.form.fieldsArea, self)
  File "aqt\editor.py", line 102, in __init__
  File "aqt\editor.py", line 142, in setupWeb
  File "aqt\hooks_gen.py", line 1410, in __call__
  File "C:\Users\Denis\AppData\Roaming\Anki2\addons21\24411424\custom_shortcuts.py", line 536, in add_preview_button
    tr(
NameError: name 'tr' is not defined
```

**Comment by The-drB** [comment]
Same me. Could you tell me how to revert to the previous version? Thanks.

**Comment by Liresol** [comment]
Hello,
Sorry about that. 
The issue should be patched out now in a new update, but if you still have issues, let me know and I will look into it as soon as possible.

**Comment by denisroutkevitch** [comment]
Yep, issue resolved!
