### ISSUE TITLE
New Glitch After Update

### ISSUE THREAD

**Issue by jchinnn** [Liresol/anki-custom-shortcuts#115]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.40 (cf446733) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-06-03 10:35:12
Hello! Love the add on, but it started glitching today after the update. I've included the info below. Could you help me locate an older version to reinstate?

Thanks!
Jessie

Add-ons possibly involved: ⁨Customize Keyboard Shortcuts⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 35, in cmd
  File "aqt/webview.py", line 124, in _onCmd
  File "aqt/webview.py", line 569, in _onBridgeCmd
  File "aqt/toolbar.py", line 170, in _linkHandler
  File "aqt/toolbar.py", line 188, in _browseLinkHandler
  File "aqt/main.py", line 1056, in onBrowse
  File "aqt/__init__.py", line 100, in open
  File "<decorator-gen-64>", line 2, in __init__
  File "anki/hooks.py", line 89, in decorator_wrapper
  File "anki/hooks.py", line 80, in repl
  File "aqt/browser.py", line 611, in __init__
  File "/Users/jessiechin/Library/Application Support/Anki2/addons21/24411424/custom_shortcuts.py", line 549, in cs_browser_setupEditor
    self.editor = Editor(self.mw, self.form.fieldsArea, self)
  File "aqt/editor.py", line 102, in __init__
  File "aqt/editor.py", line 142, in setupWeb
  File "aqt/hooks_gen.py", line 1410, in __call__
  File "/Users/jessiechin/Library/Application Support/Anki2/addons21/24411424/custom_shortcuts.py", line 536, in add_preview_button
    tr(
NameError: name 'tr' is not defined

**Comment by Liresol** [comment]
Hello,
Sorry about that. There were already reports about this (#114 ) and I've put out a patch update that should fix it.
If there are still issues, just let me know and I'll probably revert the update until things are actually fixed.

**Comment by jchinnn** [comment]
Thanks for getting back to me. Where would I locate the patch update, or does it trigger to update automatically?

**Comment by Liresol** [comment]
The patch is sent out the same way the regular updates are sent out, so your usual method of receiving updates should work. 

I'm not sure whether Anki checks for updates every time you log in, but you can also update the addons manually with the `Check for Updates` button in the addons window.
