### ISSUE TITLE
Breaking Anki 2.1.45beta3 (again..)

### ISSUE THREAD

**Issue by AnKingMed** [Liresol/anki-custom-shortcuts#118]
Here's the latest error. Triggered when clicking to open the browser screen. Looks like this verison is getting closer to public release now with the extra flags, etc

> Anki 2.1.45 (18843e71) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
> Platform: Mac 10.16
> Flags: frz=True ao=True sv=2
> Add-ons, last update check: 2021-06-25 11:49:05
> Add-ons possibly involved: ⁨Customize Keyboard Shortcuts, zkingofstudytimers⁩
> 
> Caught exception:
> Traceback (most recent call last):
>   File "aqt/webview.py", line 41, in cmd
>   File "aqt/webview.py", line 139, in _onCmd
>   File "aqt/webview.py", line 603, in _onBridgeCmd
>   File "decorator.py", line 232, in fun
>   File "anki/hooks.py", line 89, in decorator_wrapper
>   File "anki/hooks.py", line 86, in repl
>   File "/Users/Nick/Library/Application Support/Anki2/addons21/zkingofstudytimers/__init__.py", line 616, in myLinkHandler
>     return _old(self, url)
>   File "aqt/toolbar.py", line 168, in _linkHandler
>   File "aqt/toolbar.py", line 186, in _browseLinkHandler
>   File "aqt/main.py", line 1117, in onBrowse
>   File "aqt/__init__.py", line 101, in open
>   File "decorator.py", line 232, in fun
>   File "anki/hooks.py", line 89, in decorator_wrapper
>   File "anki/hooks.py", line 80, in repl
>   File "aqt/browser/browser.py", line 106, in __init__
>   File "/Users/Nick/Library/Application Support/Anki2/addons21/24411424/custom_shortcuts.py", line 524, in cs_browser_setupEditor
>     self.editor = Editor(self.mw, self.form.fieldsArea, self)
>   File "decorator.py", line 232, in fun
>   File "anki/hooks.py", line 89, in decorator_wrapper
>   File "anki/hooks.py", line 80, in repl
>   File "aqt/editor.py", line 111, in __init__
>   File "decorator.py", line 232, in fun
>   File "anki/hooks.py", line 89, in decorator_wrapper
>   File "anki/hooks.py", line 80, in repl
>   File "aqt/editor.py", line 134, in setupWeb
> KeyError: 'globalKeydown(e); '

**Comment by AnKingMed** [comment]
Looks like this may actually be another add-on... working on it
