### ISSUE TITLE
Exception after clicking on deck to learn

### ISSUE THREAD

**Issue by Robin-Haupt-1** [Liresol/anki-custom-shortcuts#133]
After click on the decks name and then on the button to start learning, i got this exception. I fixed it by updating to 2.1.49, but i thought i'd let you know.

Anki 2.1.47 (dc156f34) Python 3.8.1 Qt 5.15.1 PyQt 5.15.1
Platform: Linux
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-10-30 11:11:16
Möglicherweise beteiligte Erweiterungen: ⁨Customize Keyboard Shortcuts⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 41, in cmd
  File "aqt/webview.py", line 142, in _onCmd
  File "aqt/webview.py", line 595, in _onBridgeCmd
  File "aqt/overview.py", line 91, in _linkHandler
  File "aqt/main.py", line 672, in moveToState
  File "aqt/main.py", line 694, in _reviewState
  File "aqt/reviewer.py", line 134, in show
  File "decorator.py", line 232, in fun
  File "anki/hooks.py", line 89, in decorator_wrapper
  File "anki/hooks.py", line 86, in repl
  File "/home/robin/.local/share/Anki2/addons21/24411424/custom_shortcuts.py", line 188, in cs_review_setupShortcuts
    new_function_replacements[self.on_previous_card_info] = [config_scuts["reviewer previous card info"]]
AttributeError: 'Reviewer' object has no attribute 'on_previous_card_info'

**Comment by Liresol** [comment]
Hello,
Sorry about that.
This was broken by the most recent update, and I have just released a patch to fix the problem.
If this issue still comes up, let me know and I will look into it as soon as possible.
