### ISSUE TITLE
Update Causes Error when Using Anki

### ISSUE THREAD

**Issue by Slumboi** [Liresol/anki-custom-shortcuts#134]
The newest update ["2021-10-30: Add card info/previous card info shortcuts (2.1.45) as well as the shortcut to close the add card dialog box (2.1.20)"] causes Anki to have an error message pop up when using it. I disabled each of my add-ons to find out which one was causing the issue and when I disabled the custom shortcuts one I stopped getting the error message. To verify, I re-enabled the add-on and the error message came back. I am very used to using the Undo button so I really appreciated this custom add-on so I did not have to click control + Z each time for my Undos. 

Made this github account to report this issue. Let me know if you need more info.

**Comment by gurmyy** [comment]
Im having the same issue with the customize keyboard shortcuts add-on. Pls help

**Comment by Slumboi** [comment]
If you just want to be able to use Anki again, just disable this add-on. I also read on the add-on information page for this add-on that updating to the newest version of Anki resolved the issue for one person.  But I would not like to update my version of anki just yet, 

https://ankiweb.net/shared/info/24411424

**Comment by gurmyy** [comment]
Im really not trying to update my anki and I would rather wait for the add on to be updated. Just annoying bc im used to the undo button :(

**Comment by Slumboi** [comment]
the keyboard shortcut for it without the add-on is Control+Z

**Comment by gurmyy** [comment]
That doesn't work for me for whatever reason

**Comment by Slumboi** [comment]
are you on pc?

**Comment by gurmyy** [comment]
Im dumb...its command z on mac. all good ty

**Comment by Liresol** [comment]
Hello,
Sorry about that.
This was broken by the recent update, and I have just tried to fix the issue with a new patch.
If the issue is still there, let me know and I will try to get to it as soon as possible.

**Comment by Slumboi** [comment]
It is still giving me an error, if it helps I am on Anki 2.1.46.

**Comment by Liresol** [comment]
Can you paste the error message here?
I also know that Anki doesn't check for updates when you re-enable an addon, so there's a chance that it's still outdated.

**Comment by Slumboi** [comment]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.46 (94913ec2) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-10-30 03:35:18

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 41, in cmd
  File "aqt\webview.py", line 139, in _onCmd
  File "aqt\webview.py", line 592, in _onBridgeCmd
  File "decorator.py", line 232, in fun
  File "anki\hooks.py", line 89, in decorator_wrapper
  File "anki\hooks.py", line 86, in repl
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\review_heatmap\links.py", line 69, in heatmapLinkHandler
    return None if not _old else _old(self, url)
  File "decorator.py", line 232, in fun
  File "anki\hooks.py", line 89, in decorator_wrapper
  File "anki\hooks.py", line 84, in repl
  File "aqt\overview.py", line 91, in _linkHandler
  File "aqt\main.py", line 672, in moveToState
  File "aqt\main.py", line 694, in _reviewState
  File "aqt\reviewer.py", line 134, in show
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\864545277\review_controller.py", line 122, in customShortcut
    sList = fn(self)
  File "decorator.py", line 232, in fun
  File "anki\hooks.py", line 89, in decorator_wrapper
  File "anki\hooks.py", line 86, in repl
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\24411424\custom_shortcuts.py", line 188, in cs_review_setupShortcuts
    new_function_replacements[self.on_previous_card_info] = [config_scuts["reviewer previous card info"]]
AttributeError: 'Reviewer' object has no attribute 'on_previous_card_info'

**Comment by Liresol** [comment]
At first glance it looks like this is an error from the outdated (broken) version of the addon. You might have to use "Check for Updates" on the addon window to get the update since Anki doesn't always check automatically, but hopefully that's the issue and not something worse.

**Comment by Slumboi** [comment]
Solved the issue! thank you very much!

**Comment by gurmyy** [comment]
My undo button is still not working after uninstalling and reinstalling the add on. I am no longer receiving the error message that slumboi posted above however.

**Comment by Liresol** [comment]
Uninstalling and reinstalling will reset all the shortcuts (uninstalling deletes all saved config information), so you might just have the default undo shortcut at the moment.
