### ISSUE TITLE
UNDO FUNCTION IS NOT WORKING (CMD+Z) OR CTRL+Z

### ISSUE THREAD

**Issue by IN1OSE** [Liresol/anki-custom-shortcuts#135]
I AM RUNNING ANKI 2.1.23 

ATTACHED BELOW IS THE ERROR CODE. I NEED SOMEONE TO FIX THIS PLEASE. 

IN ADDITION IF SOMEONE CAN MAKE A SIMPLE SHORTCUT THAT CHANGES THE DEFAULT UNDO FROM CMD+SHIFT+Z TO CMD+Z THAT WOULD BE GREAT!!!

THAT IS THE ONLY REASON I USED THE APP, MADE IT SO MUCH BETTER. PLEASE FIX ASAP!!!

When loading '⁨Customize Keyboard Shortcuts⁩':
⁨Traceback (most recent call last):
  File "aqt/addons.py", line 208, in loadAddons
  File "/Users/dr__dru/Library/Application Support/Anki2/addons21/24411424/__init__.py", line 1, in <module>
    from . import custom_shortcuts
  File "/Users/dr__dru/Library/Application Support/Anki2/addons21/24411424/custom_shortcuts.py", line 680, in <module>
    gui_hooks.add_cards_did_init.append(cs_injectCloseShortcut([config_scuts["editor add card close window"]]))
AttributeError: module 'aqt.gui_hooks' has no attribute 'add_cards_did_init'

**Comment by Liresol** [comment]
Hello,
Sorry about that.
This was broken by the most recent update, and I have just released a patch to fix the issue.
If the issue is still there, let me know and I will try to get back to you as soon as I can.

**Comment by IN1OSE** [comment]
Hey thank you so much!!!!!

Its fixed now. Just updated and it works.
