### ISSUE TITLE
TypeError: onDialogOpened() got an unexpected keyword argument 'search'

### ISSUE THREAD

**Issue by masonc15** [Liresol/anki-custom-shortcuts#147]
Hello,

I am having an issue where when I am creating a card and it is a duplicate and I click on "Show Duplicates", I get the following error which seems to be related to this addon.  Any help would be appreciated.

```
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-02-01 20:45:16

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 41, in cmd
  File "aqt\webview.py", line 142, in _onCmd
  File "aqt\webview.py", line 595, in _onBridgeCmd
  File "decorator.py", line 232, in fun
  File "anki\hooks.py", line 89, in decorator_wrapper
  File "anki\hooks.py", line 86, in repl
  File "C:\Users\darks\AppData\Roaming\Anki2\addons21\24411424\custom_shortcuts.py", line 383, in cs_captureBridgeToggleSticky
    return _old(self,cmd)
  File "aqt\editor.py", line 438, in onBridgeCmd
  File "aqt\editor.py", line 564, in showDupes
  File "decorator.py", line 232, in fun
  File "anki\hooks.py", line 89, in decorator_wrapper
  File "anki\hooks.py", line 81, in repl
TypeError: onDialogOpened() got an unexpected keyword argument 'search'
```

Thanks.

**Comment by Liresol** [comment]
Hello,
Sorry for the inconvenience, but this looks like it's either an addon interaction or another addon entirely.
The particular function `onDialogOpened()` isn't in this addon or in vanilla Anki, so it might be another addon (actually it looks like [you found it already](https://github.com/glutanimate/speed-focus-mode/issues/46)), and since one of the ways to trigger it is a shortcut, the code path gets wired through this addon as well.
If it really is an addon interaction, then I can try to mitigate this issue but at this point I'm not sure whether there's anything I can do.

**Comment by masonc15** [comment]
Yep, looks to be an issue with the Speed Focus addon, not this one.  Sorry about the false issue, just got confused when this addon's ID was included in the error output.  Thanks for the response!  I'll close this out.
