### ISSUE TITLE
Unable to access browser

### ISSUE THREAD

**Issue by ccont123** [Liresol/anki-custom-shortcuts#160]
I am unable to access the deck browser mode anymore ever since the most recent update I instead get the message seen below. I currently am on anki 2.1.50. I turned off all add-ons and left this one on and the problem persisted. I then turned off all add-ons except this add on and the problem went away, so I am almost positive this issue is from the custom keyboard shortcuts.

Here is my debug info: 
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.50 (db804d95) Python 3.9.7 Qt 6.2.2 PyQt 6.2.2
Platform: Mac 12.2.1
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-04-06 13:35:18
Add-ons possibly involved: ⁨Customize Keyboard Shortcuts⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 41, in cmd
  File "aqt.webview", line 148, in _onCmd
  File "aqt.webview", line 603, in _onBridgeCmd
  File "aqt.toolbar", line 168, in _linkHandler
  File "aqt.toolbar", line 186, in _browseLinkHandler
  File "aqt.main", line 1133, in onBrowse
  File "aqt", line 124, in open
  File "aqt.browser.browser", line 129, in __init__
  File "/Users/cristiancontreras/Library/Application Support/Anki2/addons21/24411424/custom_shortcuts.py", line 691, in cs_browser_setupEditor
    self.editor = Editor(self.mw, self.form.fieldsArea, self, editor_mode=EditorMode.BROWSER,)
NameError: name 'EditorMode' is not defined

**Comment by Liresol** [comment]
Hello,
Sorry for the inconvenience. 
Since 2.1.50 is currently in beta, there might be a few issues with beta version compatibility (and there definitely is one here). 
I'm pretty sure that if you update to the most recent version of the 2.1.50 beta, this issue should be resolved.
That being said, I can probably put out a patch for this issue pretty quickly based on the behavior here.
