### ISSUE TITLE
2.1.54 Error when I try to paste

### ISSUE THREAD

**Issue by yen67** [Liresol/anki-custom-shortcuts#181]
Hi guys, 
Whenever I try to paste something that I copied beforehand,
It shows me this : 

_Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.15.2 PyQt 5.15.5
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-07-22 18:19:51

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 42, in cmd
  File "aqt.webview", line 149, in _onCmd
  File "aqt.webview", line 624, in _onBridgeCmd
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 86, in repl
  File "C:\Users\Elève\AppData\Roaming\Anki2\addons21\1593969147\__init__.py", line 558, in onBridgeCmd
    return _old(self, cmd)
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 86, in repl
  File "C:\Users\Elève\AppData\Roaming\Anki2\addons21\24411424\custom_shortcuts.py", line 440, in cs_captureBridgeToggleSticky
    return _old(self,cmd)
  File "aqt.editor", line 467, in onBridgeCmd
  File "aqt.editor", line 945, in onPaste
  File "aqt.editor", line 1204, in onPaste
  File "aqt.editor", line 1198, in _onPaste
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 86, in repl
TypeError: _processMime_around() got multiple values for argument '_old'_

Could you help me to solve this problem?
Thank you in advance for your help!

**Comment by Liresol** [comment]
Hello,
Sorry for the delay.
This looks like an issue with the interaction with another addon (Image Style Editor).
The stop-gap would be to disable one of the two addons, but in order to better figure this out could you also give any prior steps that you used to reproduce this issue?
