### ISSUE TITLE
Anki crashed - had to disable and enable anki-custom-shortcuts again

### ISSUE THREAD

**Issue by StefanBohr** [Liresol/anki-custom-shortcuts#186]
With latest version Anki stops working with anki-custom-shortcuts active (if text was pasted with STRC-V).
Restarted Anki with "disable all Extensions" option and activated all extensions except for anki-custom-shortcuts.

Error message
...
Debuginformationen:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.15.2 PyQt 5.15.5
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-08-11 15:50:40

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 42, in cmd
  File "aqt.webview", line 149, in _onCmd
  File "aqt.webview", line 624, in _onBridgeCmd
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 86, in repl
  File "C:\Users\bohr000s\AppData\Roaming\Anki2\addons21\24411424\custom_shortcuts.py", line 440, in cs_captureBridgeToggleSticky
    return _old(self,cmd)
  File "aqt.editor", line 467, in onBridgeCmd
  File "aqt.editor", line 945, in onPaste
  File "aqt.editor", line 1204, in onPaste
  File "aqt.editor", line 1198, in _onPaste
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 86, in repl
TypeError: _processMime_around_with_extended() got multiple values for argument '_old'

**Comment by Liresol** [comment]
Hello,
I'm having a bit of trouble reproducing this bug. 
Were there any steps that you took prior to this bug occurring? In particular, did you do anything with the shortcuts for `editor toggle sticky all` or `editor toggle sticky current`?
