### ISSUE TITLE
Startup failed on 23.12.1 qt6

### ISSUE THREAD

**Issue by ajf12321** [Liresol/anki-custom-shortcuts#220]
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22635

When loading Customize Keyboard Shortcuts:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\X\AppData\Roaming\Anki2\addons21\24411424\__init__.py", line 1, in <module>
    from . import custom_shortcuts
  File "C:\Users\X\AppData\Roaming\Anki2\addons21\24411424\custom_shortcuts.py", line 54, in <module>
    Qt_functions = {"Qt.Key_Enter": Qt.Key_Enter,
AttributeError: type object 'Qt' has no attribute 'Key_Enter'

**Comment by ayushchand** [comment]
Hello, the code in the dev branch works for me, There is issue with the new Anki versioning and QT6 Key bindings. Not sure why it is not in the official release.
https://github.com/Liresol/anki-custom-shortcuts/tree/dev/custom_shortcuts

**Comment by Liresol** [comment]
Hello,
The code from the dev branch is in the most recent release of this addon. I know that for some reason the version detection system doesn't inform you that a newer version is available, so a reinstall might fix the issue (if you do this remember to backup your shortcuts first since I think those get reset on reinstall).

**Comment by Andrew15-5** [comment]
Indeed. I copied the `meta.json`, then reinstalled the addon. Then I replaced the config file and for some reason the new one had `"branch_index": 2` instead of `"branch_index": 1`. But it works either way.

**Comment by jujemido** [comment]
1. Make a backup of your shortcuts, delete the version and install it again. Close Anki
2. Go here https://github.com/Liresol/anki-custom-shortcuts/tree/dev/custom_shortcuts, download "custom_shortcuts.py" and "cs_functions.py".
3. Go to the Addon Folder (I'm using mac, so It should be something like "/Users/yourusername/Library/Application Support/Anki2/addons21/24411424"
4. Replace these two files
5. Open Anki
