### ISSUE TITLE
Customize Keyboard Issue

### ISSUE THREAD

**Issue by spikyjackfruit** [Liresol/anki-custom-shortcuts#224]
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.0-arm64-arm-64bit

When loading Customize Keyboard Shortcuts:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "/Users/Personal/Library/Application Support/Anki2/addons21/24411424/__init__.py", line 1, in <module>
    from . import custom_shortcuts
  File "/Users/Personal/Library/Application Support/Anki2/addons21/24411424/custom_shortcuts.py", line 54, in <module>
    Qt_functions = {"Qt.Key_Enter": Qt.Key_Enter,
AttributeError: type object 'Qt' has no attribute 'Key_Enter'

**Comment by spikyjackfruit** [comment]
Deleting the app and reinstalling is not helping. Thank you

**Comment by Andrew15-5** [comment]
Duplicate of #220.
