### ISSUE TITLE
Add-on Startup Failed

### ISSUE THREAD

**Issue by sunrucong** [Liresol/anki-custom-shortcuts#233]
Saw on AnkiWeb that someone else encountered this problem but their fix didn't work for me. I pasted the debug info below.

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22631

When loading Customize Keyboard Shortcuts:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\ruper\AppData\Roaming\Anki2\addons21\24411424\__init__.py", line 1, in <module>
    from . import custom_shortcuts
  File "C:\Users\ruper\AppData\Roaming\Anki2\addons21\24411424\custom_shortcuts.py", line 882, in <module>
    mw.toolbar.draw()
  File "aqt.toolbar", line 274, in draw
  File "aqt.webview", line 540, in stdHtml
  File "_aqt.hooks", line 5480, in __call__
  File "C:\Users\ruper\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 4636, in inject_life_bar
    experience_for_next_lvl = find_experience_for_level(mainpokemon_growth_rate, mainpokemon_level)
  File "C:\Users\ruper\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 4338, in find_experience_for_level
    return experience
UnboundLocalError: local variable 'experience' referenced before assignment

**Comment by Liresol** [comment]
Hello,
Sorry for the delay. This looks like an interaction with another addon, namely this one:
https://ankiweb.net/shared/info/1908235722

Do you know whether disabling one of the two addons temporarily fixes the issue?
