### ISSUE TITLE
Error when trying to open up browse window

### ISSUE THREAD

**Issue by ballin4dapandas** [Liresol/anki-custom-shortcuts#26]
With this add on installed, when I try to open u the browser window I get this error: 

Debug info:
Anki 2.1.7 (a6c34fd7) Python 3.6.7 Qt 5.12.0 PyQt 5.11.3
Platform: Windows 10
Flags: frz=True ao=True sv=1

Caught exception:
  File "aqt\webview.py", line 27, in cmd
  File "aqt\webview.py", line 85, in _onCmd
  File "aqt\webview.py", line 346, in _onBridgeCmd
  File "aqt\toolbar.py", line 55, in _linkHandler
  File "aqt\toolbar.py", line 73, in _browseLinkHandler
  File "aqt\main.py", line 827, in onBrowse
  File "aqt\__init__.py", line 82, in open
  File "C:\Users\Username\AppData\Roaming\Anki2\addons21\874215009\advancedbrowser\core.py", line 275, in __init__
    origInit(self, mw)
<class 'TypeError'>: newBrowserInit() takes 2 positional arguments but 3 were given

**Comment by ballin4dapandas** [comment]
I should add that I double checked that this add on was the issue and not any of my other add ons. I'm not sure if this could be caused by an interaction with other add ons (I am not familiar with coding of any sorts) and that is a possibility I haven't checked.

**Comment by Liresol** [comment]
It looks like this is caused by an add-on interaction (the error itself is being reported in the code of Advanced Browser), though I can't seem to be able to reproduce this bug. If Advanced Browser works alone (which I assume it does), it still is an issue with this add-on, just hidden beneath more code.

Can you paste a copy of your config file? There might be a few things that I could work off of there.

**Comment by Liresol** [comment]
@Arthur-Milchior That's actually different compatibility issue, caused by certain changes in Anki 2.1.6+. I just pushed out an update that should hopefully fix this one. If it doesn't fix it, though, I'll move this to a new issue and we'll take it from there.

**Comment by shadoknaute** [comment]
Hello,
Just updated to Anki 2.1.10, and the same problem occurs to me

Here is the error message I get when trying to open the browser

Debug info:
Anki 2.1.10 (22d6feed) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Windows 10
Flags: frz=True ao=True sv=1

Caught exception:
  File "aqt\webview.py", line 27, in cmd
  File "aqt\webview.py", line 85, in _onCmd
  File "aqt\webview.py", line 360, in _onBridgeCmd
  File "aqt\toolbar.py", line 56, in _linkHandler
  File "aqt\toolbar.py", line 74, in _browseLinkHandler
  File "aqt\main.py", line 833, in onBrowse
  File "aqt\__init__.py", line 82, in open
  File "C:\Users\guill\AppData\Roaming\Anki2\addons21\874215009\advancedbrowser\core.py", line 275, in __init__
    origInit(self, mw)
  File "<decorator-gen-12>", line 2, in __init__
  File "anki\hooks.py", line 74, in decorator_wrapper
  File "anki\hooks.py", line 65, in repl
  File "aqt\browser.py", line 404, in __init__
  File "aqt\browser.py", line 469, in setupMenus
  File "anki\hooks.py", line 29, in runHook
  File "C:\Users\guill\AppData\Roaming\Anki2\addons21\24411424\custom_shortcuts.py", line 204, in cs_browser_setupShortcuts
    f.actionClear_Flag.setShortcut(config_scuts["window_browser flags_clear"])
<class 'AttributeError'>: 'Ui_Dialog' object has no attribute 'actionClear_Flag'

Thanks for the great work though :)

**Comment by Liresol** [comment]
@shadoknaute Sorry for the late response. You might be using an outdated version of Custom Shortcuts, since the error seems to be referring to code no longer present in this addon. It could be fixed by updating.

However, it might also be an interaction with the Advanced Browser addon that I'm not aware of. If updating doesn't fix it, please report back anything you have and I'll keep looking to figure out the problem.

**Comment by shadoknaute** [comment]
Hello, 
Everything works fine since I updated your add on too,
Thank you !

**Comment by WickedCheese18** [comment]
I'm getting a similar error recently (v2.1.26); it's saying:

> Debug info:
> Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
> Platform: Windows 10
> Flags: frz=True ao=True sv=2
> Add-ons, last update check: 2020-08-14 14:56:15
> 
> Caught exception:
> Traceback (most recent call last):
>   File "aqt\webview.py", line 34, in cmd
>   File "aqt\webview.py", line 114, in _onCmd
>   File "aqt\webview.py", line 518, in _onBridgeCmd
>   File "aqt\toolbar.py", line 154, in _linkHandler
>   File "aqt\toolbar.py", line 172, in _browseLinkHandler
>   File "aqt\main.py", line 1022, in onBrowse
>   File "aqt\__init__.py", line 95, in open
>   File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-86>", line 2, in __init__
>   File "lib\site-packages\anki\hooks.py", line 638, in decorator_wrapper
>   File "lib\site-packages\anki\hooks.py", line 629, in repl
>   File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-66>", line 2, in __init__
>   File "lib\site-packages\anki\hooks.py", line 638, in decorator_wrapper
>   File "lib\site-packages\anki\hooks.py", line 629, in repl
>   File "aqt\browser.py", line 600, in __init__
>   File "C:\Users\lawso\AppData\Roaming\Anki2\addons21\24411424\custom_shortcuts.py", line 408, in cs_browser_setupEditor
>     self.editor = Editor(self.mw, self.form.fieldsArea, self)
>   File "aqt\editor.py", line 92, in __init__
>   File "aqt\editor.py", line 173, in setupWeb
>   File "lib\site-packages\anki\hooks.py", line 594, in runFilter
>   File "C:\Users\lawso\AppData\Roaming\Anki2\addons21\2053932397\editor.py", line 85, in setupEditorButtonsFilter
>     editor.addButton(
>   File "aqt\editor.py", line 230, in addButton
>   File "aqt\editor.py", line 255, in _addButton
>   File "aqt\editor.py", line 204, in resourceToData
> FileNotFoundError

**Comment by Liresol** [comment]
Sorry @WickedCheese18 , I think this is caused either by an addon interaction with the addon ID 2053932397 or by another addon going out of date. 
Unfortunately looks like this other addon isn't shared anymore, so unless you can somehow share that addon there's not much more I can do to fix that particular issue.

**Comment by WickedCheese18** [comment]
@Liresol I was able to find the addon that was giving the issue and remove it. Thank you for providing the direction to resolve this; my apologies for flagging it on your addon.
