### ISSUE TITLE
Incompatible with Anki 2.1.21beta2

### ISSUE THREAD

**Issue by AnKingMed** [Liresol/anki-custom-shortcuts#58]
Tried using beta2 and beta3 this morning and I get an error whenever I open Anki: When loading '⁨Customize Keyboard Shortcuts⁩':
⁨Traceback (most recent call last):
  File "aqt/addons.py", line 207, in loadAddons
  File "/Users/Nick/Library/Application Support/Anki2/addons21/24411424/__init__.py", line 1, in <module>
    from . import custom_shortcuts
  File "/Users/Nick/Library/Application Support/Anki2/addons21/24411424/custom_shortcuts.py", line 338, in <module>
    mw.toolbar.draw()
  File "aqt/toolbar.py", line 48, in draw
  File "/Users/Nick/Library/Application Support/Anki2/addons21/24411424/custom_shortcuts.py", line 303, in cs_toolbarCenterLinks
    return self._linkHTML(links)
AttributeError: 'Toolbar' object has no attribute '_linkHTML'

**Comment by glutanimate** [comment]
Sorry, meant to ping you earlier, @liresol. Related Anki PR & discussion: https://github.com/ankitects/anki/pull/448#issuecomment-586649595

**Comment by Liresol** [comment]
It's really my fault for leaving this addon behind a little, but I have fewer pressing things this week so I'm looking to try to resolve these issues soon.

**Comment by Liresol** [comment]
Pushed out something that should make this compatible with 2.1.21.

It works on my machine™, but I'm keeping this issue open until I'm sure that it works for everyone.

**Comment by AnKingMed** [comment]
Just downloaded the update. I'd recommend altering the code so the add-on differs based on whether the user is using .20 or .21 as anyone that downloads this update will no longer be able to use the add-on versions prior to .21beta at the moment

**Comment by Liresol** [comment]
The new code does implement a version check, but if you are having issues with .20, I'll look back and check again if it works.

**Comment by AnKingMed** [comment]
I tried 2.1.20 and 2.1.21beta1 and neither worked.  I'm on 2.1.21beta3 now and its working fine.  

Here's the error on 2.1.20:
addons21/anki_background_image_in_main_window/__init__.py", line 84, in <module>
    gui_hooks.webview_will_set_content.append(replace_css)
AttributeError: module 'aqt.gui_hooks' has no attribute 'webview_will_set_content'

**Comment by Liresol** [comment]
That actually looks like an issue with a different addon ([this one?](https://github.com/ijgnd/anki__background_image_in_main_window)), but it might be caused by addon interactions. 

I'm getting errors with that one alone in .20, but I'll check if this addon has anything to do with it.

**Comment by AnKingMed** [comment]
Aw shoot you're right. I'm sorry I should have paid more attention.  I'm studying for a final and have just been monitoring this quickly (apparently too quickly...)

**Comment by Liresol** [comment]
No worries, sometimes issues like that wind up being relevant so they're not always a waste to bring up.

**Comment by AnKingMed** [comment]
I've been testing around 10 different add-ons for different developers and its been  a little crazy.  This one does seem to be working properly on all versions now though. Thanks for the quick update!
