### ISSUE TITLE
Cannot bind 'reviewer replay audio 1' in 'reviewer_duplicates' (KeyError)

### ISSUE THREAD

**Issue by SimonLammer** [Liresol/anki-custom-shortcuts#80]
I'd like audio to be played upon pressing 'u' - as 'reviewer_duplicate', original is and should stay 'r' - so I can access it with my right-hand.
When I try to start reviewing an error message pops up with the following debug info:

```
Anki 2.1.26 (70784154) Python 3.8.1 Qt 5.14.1 PyQt 5.14.1
Platform: Linux
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-08-18 17:49:44
Add-ons possibly involved: ⁨Customize Keyboard Shortcuts, Heatmap⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 34, in cmd
  File "aqt/webview.py", line 114, in _onCmd
  File "aqt/webview.py", line 518, in _onBridgeCmd
  File "</opt/anki/bin/decorator.pyc:decorator-gen-14>", line 2, in _linkHandler
  File "anki/hooks.py", line 638, in decorator_wrapper
  File "anki/hooks.py", line 635, in repl
  File "/home/slammer/.local/share/Anki2/addons21/1722241614/links.py", line 74, in heatmapLinkHandler
    return None if not _old else _old(self, url)
  File "aqt/overview.py", line 67, in _linkHandler
  File "aqt/main.py", line 632, in moveToState
  File "aqt/main.py", line 655, in _reviewState
  File "aqt/reviewer.py", line 61, in show
  File "/home/slammer/.local/share/Anki2/addons21/24411424/custom_shortcuts.py", line 153, in cs_review_setupShortcuts
    dupes.append((config_scuts["reviewer _duplicates"][scut],self.sToF(scut)))
  File "/home/slammer/.local/share/Anki2/addons21/24411424/cs_functions.py", line 74, in review_sToF
    return sdict[scut]
KeyError: 'reviewer replay audio 1'
```

I've tried keys different to 'u', but the same error occured.

My config: (I havn't changed anything besides reviewer hotkeys)
```
{
    "editor _duplicates": {},
    "editor _extras": {
        "paste custom text": "<nop>"
    },
    "editor _pastes": {},
    "editor add media": "F3",
    "editor bold": "Ctrl+B",
    "editor card layout": "Ctrl+L",
    "editor change col": "F8",
    "editor cloze": "Ctrl+Shift+C",
    "editor cloze alt": "Ctrl+Shift+Alt+C",
    "editor cloze forced increment": "<nop>",
    "editor cloze no increment": "<nop>",
    "editor focus tags": "Ctrl+Shift+T",
    "editor foreground": "F7",
    "editor html edit": "Ctrl+Shift+X",
    "editor insert latex": "Ctrl+T, T",
    "editor insert latex equation": "Ctrl+T, E",
    "editor insert latex math environment": "Ctrl+T, M",
    "editor insert mathjax block": "Ctrl+M, E",
    "editor insert mathjax chemistry": "Ctrl+M, C",
    "editor insert mathjax inline": "Ctrl+M, M",
    "editor italic": "Ctrl+I",
    "editor record sound": "F5",
    "editor remove format": "Ctrl+R",
    "editor subscript": "Ctrl+=",
    "editor superscript": "Ctrl++",
    "editor underline": "Ctrl+U",
    "m_toolbox _duplicates": {},
    "m_toolbox addons": "Ctrl+Shift+A",
    "m_toolbox create filtered deck": "F",
    "m_toolbox export": "Ctrl+E",
    "m_toolbox import": "Ctrl+Shift+I",
    "m_toolbox preferences": "Ctrl+P",
    "m_toolbox quit": "Ctrl+Q",
    "m_toolbox see documentation": "F1",
    "m_toolbox study": "/",
    "m_toolbox switch profile": "Ctrl+Shift+P",
    "m_toolbox undo": "Ctrl+Z",
    "main add": "A",
    "main browse": "B",
    "main debug": "Ctrl+:",
    "main deckbrowser": "D",
    "main stats": "<nop>",
    "main study": "S",
    "main sync": "Y",
    "reviewer _duplicates": {
        "reviewer bury card": "-",
        "reviewer bury note": "Alt+-",
        "reviewer choice 1": "0",
        "reviewer choice 2": "9",
        "reviewer choice 3": "8",
        "reviewer choice 4": "7",
        "reviewer edit current": "i",
        "reviewer mark card": "o",
        "reviewer replay audio 1": "u",
        "reviewer suspend card": "p",
        "reviewer suspend note": "Alt+p"
    },
    "reviewer bury card": "`",
    "reviewer bury note": "Alt+`",
    "reviewer choice 1": "1",
    "reviewer choice 2": "2",
    "reviewer choice 3": "3",
    "reviewer choice 4": "4",
    "reviewer delete note": "Ctrl+Delete",
    "reviewer edit current": "E",
    "reviewer flip card 1": " ",
    "reviewer flip card 2": "Qt.Key_Return",
    "reviewer flip card 3": "Qt.Key_Enter",
    "reviewer mark card": "w",
    "reviewer options menu": "<nop>",
    "reviewer pause audio": "5",
    "reviewer play recorded voice": "v",
    "reviewer record voice": "Shift+v",
    "reviewer replay audio 1": "r",
    "reviewer replay audio 2": "F5",
    "reviewer seek backward": "6",
    "reviewer seek forward": "<nop>",
    "reviewer set flag 0": "Ctrl+0",
    "reviewer set flag 1": "Ctrl+1",
    "reviewer set flag 2": "Ctrl+2",
    "reviewer set flag 3": "Ctrl+3",
    "reviewer set flag 4": "Ctrl+4",
    "reviewer suspend card": "q",
    "reviewer suspend note": "Alt+q",
    "window_browser _filters": {
        "_concat": {},
        "_orConcat": {}
    },
    "window_browser add note": "Ctrl+E",
    "window_browser add tag": "Ctrl+Shift+A",
    "window_browser change deck": "Ctrl+D",
    "window_browser change note type": "Ctrl+Shift+M",
    "window_browser clear unused tags": "<nop>",
    "window_browser close": "Ctrl+W",
    "window_browser delete": "Ctrl+Del",
    "window_browser filter": "Ctrl+Shift+F",
    "window_browser find": "Ctrl+F",
    "window_browser find and replace": "Ctrl+Alt+F",
    "window_browser find duplicates": "<nop>",
    "window_browser first card": "Home",
    "window_browser flag_blue": "Ctrl+4",
    "window_browser flag_green": "Ctrl+3",
    "window_browser flag_orange": "Ctrl+2",
    "window_browser flag_red": "Ctrl+1",
    "window_browser goto card list": "Ctrl+Shift+L",
    "window_browser goto next note": "Ctrl+N",
    "window_browser goto note": "Ctrl+Shift+N",
    "window_browser goto previous note": "Ctrl+P",
    "window_browser goto sidebar": "Ctrl+Shift+R",
    "window_browser guide": "F1",
    "window_browser info": "Ctrl+Shift+I",
    "window_browser invert selection": "Ctrl+Alt+S",
    "window_browser last card": "End",
    "window_browser manage note types": "<nop>",
    "window_browser preview": "Ctrl+Shift+P",
    "window_browser remove current filter": "<nop>",
    "window_browser remove tag": "Ctrl+Shift+D",
    "window_browser reposition": "Ctrl+Shift+S",
    "window_browser reschedule": "Ctrl+Alt+R",
    "window_browser save current filter": "<nop>",
    "window_browser select all": "Ctrl+Alt+A",
    "window_browser select notes": "<nop>",
    "window_browser suspend": "Ctrl+J",
    "window_browser toggle mark": "Ctrl+K",
    "window_browser undo": "Ctrl+Alt+Z",
    "Ω custom paste end style": "n",
    "Ω custom paste extra texts": {},
    "Ω custom paste text": "",
    "Ω enable conflict warning": "y",
    "Ω enable editor": "y",
    "Ω enable m_toolbox": "y",
    "Ω enable main": "y",
    "Ω enable reviewer": "y",
    "Ω enable window_browser": "y"
}
```

When I remove the line `"reviewer replay audio 1": "u",` in `reviewer_duplicates` the config works fine. (without the bound audio replay - obviously)

**Comment by Liresol** [comment]
Hello, sorry for that issue. 
I have just pushed out an update that should fix this, but if anything comes up, please let me know and I will look into it further.

**Comment by SimonLammer** [comment]
Works like a charm. Thanks for the quick fix!
