### ISSUE TITLE
Anki 2.1.39beta1 suggests this needs a change moving forward

### ISSUE THREAD

**Issue by AnKingMed** [Liresol/anki-custom-shortcuts#99]
Looks like because the preview button was moved this may need a small update for future versions and I wanted to give you a heads up. Lemme know if you need help testing anything!

```
Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 35, in cmd
  File "aqt/webview.py", line 124, in _onCmd
  File "aqt/webview.py", line 569, in _onBridgeCmd
  File "<decorator-gen-180>", line 2, in _linkHandler
  File "anki/hooks.py", line 89, in decorator_wrapper
  File "anki/hooks.py", line 86, in repl
  File "/Users/Nick/Library/Application Support/Anki2/addons21/zkingofstudytimers/__init__.py", line 607, in myLinkHandler
    return _old(self, url)
  File "aqt/toolbar.py", line 170, in _linkHandler
  File "aqt/toolbar.py", line 188, in _browseLinkHandler
  File "aqt/main.py", line 1048, in onBrowse
  File "<decorator-gen-168>", line 2, in open
  File "anki/hooks.py", line 89, in decorator_wrapper
  File "anki/hooks.py", line 80, in repl
  File "aqt/__init__.py", line 101, in open
  File "/Users/Nick/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 206, in __init__
    origInit(self, mw)
  File "<decorator-gen-188>", line 2, in __init__
  File "anki/hooks.py", line 89, in decorator_wrapper
  File "anki/hooks.py", line 80, in repl
  File "aqt/browser.py", line 471, in __init__
  File "aqt/browser.py", line 532, in setupMenus
  File "aqt/hooks_gen.py", line 526, in __call__
  File "anki/hooks.py", line 34, in runHook
  File "/Users/Nick/Library/Application Support/Anki2/addons21/24411424/custom_shortcuts.py", line 259, in cs_browser_setupShortcuts
    f.previewButton.setShortcut(config_scuts["window_browser preview"])
AttributeError: 'Ui_Dialog' object has no attribute 'previewButton'
```

**Comment by Liresol** [comment]
Hello,
Thanks for the heads up.
I pushed out an update for this and tested it on my machine with the 2.1.39 beta.
It should work now, but let me know if you encounter any other strange things.

**Comment by AnKingMed** [comment]
Awesome! Thanks as always!
